CREATE DATABASE `weibo-poi`;

CREATE TABLE `weibo-poi`.`poi-user-上海` (
    `poi_id` VARCHAR(255) NOT NULL COMMENT 'POI标识',
    `poi_category` VARCHAR(255) NULL COMMENT 'POI类别',
    `poi_lat` VARCHAR(255) NULL COMMENT 'POI纬度',
    `poi_lng` VARCHAR(255) NULL COMMENT 'POI经度',
    `poi_name` VARCHAR(255) NULL COMMENT 'POI名称',
    `poi_address` VARCHAR(255) NULL COMMENT 'POI地址',
    `user_id` VARCHAR(255) NOT NULL COMMENT '用户ID',
    `user_name` VARCHAR(255) NULL COMMENT '用户名',
    `user_profile` VARCHAR(255) NULL COMMENT '用户简介',
    `user_age` VARCHAR(255) NULL COMMENT '用户年龄',
    `user_xingzuo` VARCHAR(255) NULL COMMENT '用户星座',
    `user_degree` VARCHAR(255) NULL COMMENT '用户学历',
    `user_iphone` VARCHAR(255) NULL COMMENT '用户手机号',
    `user_sex` VARCHAR(255) NULL COMMENT '用户性别',
    `user_company` VARCHAR(255) NULL COMMENT '用户公司',
    `user_register_time` VARCHAR(255) NULL COMMENT '用户注册时间',
    `user_credit_level` VARCHAR(255) NULL COMMENT '用户信用等级',
    `user_followers` VARCHAR(255) NULL COMMENT '用户粉丝数',
    `user_friends` VARCHAR(255) NULL COMMENT '用户好友数',
    `user_share` VARCHAR(255) NULL COMMENT '用户分享数',
    `user_ip` VARCHAR(255) NULL COMMENT '用户IP',
    `user_location` VARCHAR(255) NULL COMMENT '用户位置',
    `user_auth` VARCHAR(255) NULL COMMENT '用户认证信息',
    `user_svip_level` VARCHAR(255) NULL COMMENT '用户SVIP等级',
    `blog_id` VARCHAR(255) NOT NULL COMMENT '博客ID',
    `blog_time_units` VARCHAR(255) NULL COMMENT '博客时间单位',
    `blog_time_stamp` VARCHAR(255) NULL COMMENT '博客时间戳',
    `blog_text` VARCHAR(255) NULL COMMENT '博客文本内容',
    `blog_repost` VARCHAR(255) NULL COMMENT '博客转发数',
    `blog_attitude` VARCHAR(255) NULL COMMENT '博客态度',
    `blog_comment` VARCHAR(255) NULL COMMENT '博客评论数',
    PRIMARY KEY (`user_id`, `blog_id`, `poi_id`),
    INDEX `idx_poi_id` (`poi_id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_blog_id` (`blog_id`),
    INDEX `idx_poi_location` (`poi_lat`, `poi_lng`),
    INDEX `idx_user_location` (`user_location`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微博POI用户信息表';    